# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  run-static-test:
    # Specify the execution environment. Here we use Python for running tests.
    docker:
      - image: cimg/python:3.11

    # Add steps to the job
    steps:
      - checkout
      - run:
          name: "Install Python dependencies"
          command: |
            pip install --user -r requirements.txt
      - run:
          name: "Run StaticTest with Coverage"
          command: |
            # Run tests with coverage
            coverage run --omit="mcpi/*" -m unittest StaticTest.py
            # Generate coverage report
            coverage report -m

# Orchestrate jobs using workflows
workflows:
  static-test-workflow:
    jobs:
      - run-static-test