# pragma: no cover
insults = [
    "Eres tan lamentable que pegas a los bloques?",
    "No sabia que eras tan bueno escavando con la espada!",
    "Espadatierra!!",
    "sigue cortando el cesped cara huevo",
    "Tu inteligencia es como una antorcha apagada.",
    "Si la estupidez fuera un superpoder, serías el héroe más fuerte.",
    "Tus ideas son tan planas como un terreno sin árboles.",
    "Tu habilidad para construir es menor que la de un pollo con patas de barro.",
    "Pensé que sabía lo que era no saber nada, hasta que te conocí.",
    "Tu estrategia es tan efectiva como usar un cubo de agua contra el fuego de lava.",
    "Te llamas minero pero solo has visto oro en los sueños de otros.",
    "Tu lógica es tan clara como el fondo del océano en noche sin luna.",
    "Si la torpeza fuera un juego, serías el campeón indiscutible.",
    "Tu creatividad es tan limitada como una caja de arena sin pala.",
    "Eres tan útil como un barco en el desierto.",
    "Tu habilidad con el arco es legendaria, entre los ciegos.",
    "Si el esfuerzo fuera dinero, estarías en bancarrota.",
    "Tienes menos sentido de dirección que una brújula en una tormenta de nieve.",
    "Tu habilidad para encontrar diamantes es menor que la de un topo con gafas.",
    "Eres más perdido que un zombi en un laberinto de setas.",
    "Tu construcción parece más un accidente que un diseño.",
    "Si esto fuera una competencia de torpes, tendrías medalla de oro.",
    "Tu habilidad con las herramientas es como la de un pez con una caña.",
    "Tu sentido común es más raro que un dragón en el Nether.",
    "Tu inteligencia es más afilada que un palo de madera.",
    "Si la paciencia fuera un recurso, tú estarías en quiebra.",
    "Eres tan bueno en esto como un esqueleto en un concurso de belleza.",
    "Tu habilidad para planear es como la de un pollo intentando volar.",
    "Tu destreza con la espada es menos impresionante que un slime peleando.",
    "Tu capacidad para seguir instrucciones es como la de un creeper cerca de un jugador.",
    "Tu nivel de habilidad es como el de una vaca tratando de saltar una valla.",
    "Eres tan bueno en esto como un enderman en una piscina.",
    "Tu sentido de la orientación es tan bueno como el de una araña en un túnel.",
    "Tu habilidad para coordinar es menor que la de una gallina en un gallinero.",
    "Si esto fuera un juego de habilidad, te habrían descalificado en la primera ronda.",
    "Tu estrategia es tan efectiva como un escudo de papel.",
    "Tu habilidad para sobrevivir es como la de un cerdo en una carnicería.",
    "Tu creatividad es tan inspiradora como una roca en una habitación vacía.",
    "Eres tan hábil como un aldeano en una batalla.",
    "Tu manera de resolver problemas es como la de un ghast en un laberinto.",
    "Si el ingenio fuera una moneda, tú estarías mendigando."
]